[project]
name = "stac-indexer"
version = "0.1.0"
description = "Index STAC catalogs into schema.org JSON-LD / RDF"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pystac>=1.14.1",
    "pystac-client>=0.8.1",
    "requests",
    "icecream",
    "s2sphere",
    "stac-validator",
    "pandas",
    "jsonschema"
]

[dependency-groups]
dev = [
    "jupyter",
]

[tool.uv]
package = false
