direction: right

classes: {
  kgclass: {
    width: 220
    style: {
      stroke-width: 0
      fill: "#008080"
      shadow: true
      border-radius: 5
    }
  }
  propclass: {
    width: 220
    style: {
      stroke-width: 0
      fill: "#FF7F50"
      shadow: true
      border-radius: 5
    }
  }
         srcclass: {
    width: 220
    style: {
      stroke-width: 0
      fill: orange
      shadow: true
      border-radius: 5
    }
  }
  genclass: {
    width: 220
    style: {
      stroke-width: 0
      fill: "#40E0D0"
      shadow: true
      border-radius: 5
    }
  }
}

*.class: genclass
stac.class: srcclass

stac: STAC Catalog
c: croissant
jld: JSON-LD \n schema.org/Dataset
sw: NEON Challenge Software
sb: STAC Browser
sm: sitemap.xml

cdapi: CODATA \n CDIF API descriptor

stac -> jld: used to generate
stac -> sm: used to generate

stac -> cdapi: used to generate

cdapi <- jld:  references

sm -> jld: points to
# sm <- jld: used to generate

jld -> stac: points back to
jld -> sw: references software that can use the data
jld -> sb: points to online representation of resource
jld -> c: points to Croissant record about the same datga

c.class: propclass
sb.class: propclass
sw.class: propclass

kg: Generated \n Knowledge Graph

con_sdg: UN SDGs
con_gc: Grand Challenge
con_dec: DeCODER
con_gds: Google \n Data Set Search
con_okn: NSF ProtoOKN
con_pub: Publications

con_*.class: kgclass

jld -> kg

        kwg: KnowWhere Graph

kg -> con_sdg
kg -> con_gc
kg -> con_dec
kg -> con_gds
kg -> con_okn
kg -> con_pub
kg -> kwg -> Historical weather events

con_dec -> search for water temp


